### ISSUE TITLE
Engine.Remove called twice

### ISSUE THREAD

**Issue by leopripos** [sebas77/Svelto.ECS#10]
https://github.com/sebas77/Svelto.ECS/blob/ed9e073ff17c98f44be43e3f741215daea30e2b0/ECS/Profiler/EngineProfiler.cs#L37

INodeEngine.Remove called twice, in `removeFunc(engine,node)` and `engine.Remove(node)`

**Comment by sebas77** [comment]
thanks I'll check it asap! I am finalizing the 1.0 release as Svelto.ECS 2.0 is now complete and will soon be released in alpha stage (need to be used in production for a while before it will replace the current master), but it's good if I fix the 1.0 bugs as well.

**Comment by leopripos** [comment]
I checked the alpha branch (first draft 2.0), it is also exsist.

**Comment by sebas77** [comment]
Well spotted, however don't overuse the EngineProfiler, it should be normally off.
