### ISSUE TITLE
Errors in readme

### ISSUE THREAD

**Issue by emelrad12** [sebas77/Svelto.ECS#118]
Copy pasting the provded example results in an error as there is no "ExclusiveGroups.group0" defined. Correcting it to SimpleContext.group0, seems to compile but running further it throws 
"System.InvalidCastException: 'Unable to cast object of type 'Svelto.DataStructures.NBInternal`1[EntityComponent]' to type 'Svelto.DataStructures.NB`1[EntityComponent]'.'"

using svelto 3.4.6 .net 7

**Comment by sebas77** [comment]
change the readme copying and pasting the hello world example
