### ISSUE TITLE
[3.5.0-pre] Filter.Add behavior changed, throws exeption

### ISSUE THREAD

**Issue by g-jozsef** [sebas77/Svelto.ECS#120]
when adding the entity twice to a filter it now throws an  exception instead of returning false
https://github.com/sebas77/Svelto.ECS/blob/bc53d38dcfc07ca3237ffa701f9d979cc4249441/com.sebaslab.svelto.ecs/Core/Filters/EntityFilterCollection.cs#L222

`            public void Add(uint entityId, uint indexInComponentArray)`
used to be
`            public bool Add(uint entityId, uint indexInComponentArray)`

**Comment by sebas77** [comment]
I do not remember at all why I changed this behaviour, but I 100% changed it purposely. We need to discuss what I could possibly wanted to avoid and pros and cons
