### ISSUE TITLE
[3.5.0-pre] Group compound warning triggers for Svelto base types

### ISSUE THREAD

**Issue by g-jozsef** [sebas77/Svelto.ECS#121]
`Group compound/tag Svelto.ECS.GroupTag`1[....] is not sealed. GroupCompounds and Tags cannot be inherited, consider marking it s
ealed`

The problem seems to be that `` is called recursively and the base svelto GroupTag and compound is also checked when they obviously can't be sealed.

https://github.com/sebas77/Svelto.ECS/blob/bc53d38dcfc07ca3237ffa701f9d979cc4249441/com.sebaslab.svelto.ecs/Core/Groups/GroupHashMap.cs#L111

**Comment by sebas77** [comment]
fixed
