### ISSUE TITLE
Preallocating after entities have been created results in corrupting the entity reference table.

### ISSUE THREAD

**Issue by bpeake13** [sebas77/Svelto.ECS#123]
If you preallocate after any entities have been created, it can result in a corrupted entity reference lookup on some indices.

Repro Steps:
- Create two entities of different descriptors in different groups
- Preallocate those groups
- Try to convert a entity reference on both of the entities to a EGID, one should be broken

**Comment by sebas77** [comment]
this actually makes sense because with the preallocation you are changing the size of the sets which invalidates the entity references because the indices will change.

**Comment by sebas77** [comment]
ok changed the code to throw an exception if preallocation is called when entities are already submitted
