### ISSUE TITLE
QueryGroupedEntityViews() : cast Dictionary to FasterList

### ISSUE THREAD

**Issue by leopripos** [sebas77/Svelto.ECS#13]
https://github.com/sebas77/Svelto.ECS/blob/d37c91eb990c9f8d548bd7da0f78ab9ee306d51a/Svelto.ECS/EntityViewsDB.cs#L39

This casting causing FasterReadOnlyList has null FasterList (_list field).

**Comment by sebas77** [comment]
well this proves that I need to write unit tests for the library. Fixing it soon, thanks a lot!

**Comment by leopripos** [comment]
Yeah, build its unit tests is a good idea.
Thanks a lot.

**Comment by sebas77** [comment]
this should be fixed now, please let me know.
