### ISSUE TITLE
GenericEntityFunctions and EnginesRoot relation

### ISSUE THREAD

**Issue by leopripos** [sebas77/Svelto.ECS#14]
https://github.com/sebas77/Svelto.ECS/blob/292e5e51d32cf8f8e77298dbdd9c10c62e58cabd/Svelto.ECS/EnginesRootEntities.cs#L364

`GenericEntityFunctions.RemoveEntityFromGroup<>()` call `EnginesRoot.RemoveEntity<T>()` instead of `EnginesRoot.RemoveEntityFromGroup<T>()`

https://github.com/sebas77/Svelto.ECS/blob/292e5e51d32cf8f8e77298dbdd9c10c62e58cabd/Svelto.ECS/EnginesRootEntities.cs#L359

`GenericEntityFunctions.RemoveMetaEntity<T>()` call `EnginesRoot.RemoveEntity<T>()` instead of `EnginesRoot.RemoveMetaEntity<T>()`

Are they bugs?
I don't understand exactly how the internal framework work, but `GenericEntityFunctions.RemoveEntityFromGroup<T>` seemed to be calling `EnginesRoot.RemoveEntityFromGroup<T>`.

**Comment by sebas77** [comment]
I'll check asap and come back to you. When I tested it, it worked with and without groups. I think the vanilla code should have a working case.

**Comment by leopripos** [comment]
I think we should make clear description about the API. Here is  assumption now, please clarify.

```csharp 
void RemoveEntity(int entityID, IRemoveEntityComponent removeInfo) ;
void RemoveEntity<T>(int entityID);
```
This is remove entity from the framework like `UnityEngine.Gameobject.Destroy()`, so it  __can not__ be accessed using `IEntityViewsDB.QueryEntityView<T>()` anymore.


```csharp 
viod RemoveMetaEntity<T>(int metaEntityID);
``` 
This is remove meta entity from the framework like `UnityEngine.Gameobject.Destroy()`, so it  __can not__ be accessed using `IEntityViewsDB.QueryMetaEntityView<T>()` anymore. 

```csharp 
void RemoveEntityFromGroup<T>(int entityID, int groupID);
```
This is remove entity from its group without remove the entity from the framework, so it  __still can__  be accessed `IEntityViewsDB.QueryEntityView<T>()`

```csharp 
void RemoveGroupedEntities(int groupID);
```
This is remove all entities in a group so the entities  __can not__ be accessed from `IEntityViewsDB.QueryEntityView<T>()` anymore.

Other note:
1. No API for grouping Meta Entity
2. No API for removing Entity Group

**Comment by sebas77** [comment]
I am checking the problems now however once you remove an entity is removed from the whole database regardless the function used and if it's inside a group or not. If this is not the case, it's a bug.

**Comment by leopripos** [comment]
Thanks, and sorry for taking free your time.
:)

**Comment by sebas77** [comment]
Other questions:

why do you need to group meta entities? Is it clear what they are for? I can't see a reason to group meta entities, unless you have something very complex in mind :)

I am renaming RemoveGroupedEntities to EmptyOutEntityGroup. thoughts?

**Comment by leopripos** [comment]
I don't mean to say that I need grouping meta entity. It just note to ensure. :)

What will `DeleteEntityGroup` do? Removing `just the group` or removing `the group and its entities`?

**Comment by sebas77** [comment]
Ok I'll rename to DeleteGroupAndRemoveItsEntitiesFromDB :)

**Comment by leopripos** [comment]
Wow, hahaha

Btw, I don't have any problem with `RemoveGroupedEntities <T>` name, so you don't need to rename it. We just need make clear description about what that method for. 

if I am allowed to conclude, you prefer to remove the group implicitly if the group does not have any more entities.

So, 
```csharp
void RemoveEntity<T>(int entityID);
void RemoveEntity(int entityID, IRemoveEntityComponent removeInfo) ;
void RemoveEntityFromGroup<T>(int entityID, int groupID);
void RemoveGroupedEntities(int groupID);
```
Will also remove the group implicitly if the group does not have any more entities.

am I right?

**Comment by sebas77** [comment]
Yes that is what it does

**Comment by sebas77** [comment]
the discussion continues on the other issue
