### ISSUE TITLE
QueryEntityViewsAsArray null reference becase its size is changing during iteration.

### ISSUE THREAD

**Issue by Darelbi** [sebas77/Svelto.ECS#18]
Ok I found a really minor bug, but maybe it can be useful, maybe it was just a undocumented behaviour

Reproducing the bug:

            int count;
            var views = entityViewsDB.QueryEntityViewsAsArray< GeometrySourceView>(out count);

            for( int i=0; i< count; i++)
            {
                entitiesSink.RemoveEntity( views[i].id.ID); // null reference at some point
            }

When iterating a array of entities taken from the entityViewsDB if I remove them in a loop I get a null reference exception. I didn't investigated yed but I assume the array is resized as long as entities are removed. I expected this kind of stuff to happen only during "SubmitEntityViews" phase.

How I fixed it (basically copying the array locally)

            var views = entityViewsDB.QueryEntityViews< GeometrySourceView>().ToArray(); // linq copy

            for( int i=0; i< views.Count(); i++)
            {
                entitiesSink.RemoveEntity( views[i].id.ID);
            }

Also what's the difference between QueryEntityViews and QueryEntityViewsAsArray? when I should prefer one to the other?

In both cases the array is resized dynamically. Now, using "AsArray" allowed me to find the bug early because of null reference (but in the second code snippet, if I remove the ".ToArray()" I will stop getting the error (of course because "view.Count" changed accordingly) and noticing the bug become harder.

**Comment by sebas77** [comment]
The array version is to be used for performance critical code where you wouldn't remove the entity very likely :)

**Comment by sebas77** [comment]
Also you don't need the ToArray

**Comment by sebas77** [comment]
To avoid these problems I could remove the entities the next frame like I do for the adding

**Comment by Darelbi** [comment]
Without the ToArray not all entities are removed. Because even though the "Count" is updated, the index "i" will miss some entities. (just tested it)

**Comment by sebas77** [comment]
Yes of course. The solution would be to do i-- but it makes sense only if
you assume how the entities are removed.

I have already wrote a method to remove all the entities from a group, I
could do one to remove all the entities built from a specific entity
descriptor which is not what you are doing. Then again what is a entity?
It's a collection of data with an unique id, therefore is probably wrong to
identify a set of entities from a entity view type (beside different entity
descriptors could generate the same entity view!) . You should know instead
the list of entity ids to delete. If in your, maybe atypical, case you want
to know the ids from the entity views, you should fill an array of ids
first.
It's more or less what you did with ToArray but it makes more sense.

**Comment by sebas77** [comment]
do you think this is still an issue @Darelbi ?

**Comment by Darelbi** [comment]
Nope Sorry didnt have time to respond.

Il giovedì 22 marzo 2018, Sebastiano Mandalà <notifications@github.com> ha
scritto:
