### ISSUE TITLE
Svelto.Common submodule is outdated

### ISSUE THREAD

**Issue by DeoVolenteGames** [sebas77/Svelto.ECS#19]
Svelto.ECS can't be used by itself because it uses the updated `DBC`<sup>[1] [2] [3]</sup> namespace while the included Svelto.Common submodule is still using the old [`DesignByContract`][old-dbc] namespace. From my testing updating Svelto.Common from [its current state](https://github.com/sebas77/Svelto.Common/commits/533a86b6a8869fd0ef83dc2a7da557b745fd7290) to [the latest commit](https://github.com/sebas77/Svelto.Common/commits/460c00846a3b547c4567aec8bdfff82a9861869c) clears this particular bug. 

*Note:*
For me it's a bit of a problem using submodules because I can't find a way to prevent submodule recursion in GitKraken. I don't know what the solution to this would be - apart from switching git clients - but for now I will stick to only learning Svelto.ECS and leave Svelto.Tasks for later. 

[1]: ../blob/23580f381d4c3f38416325b889c14862d4b00406/Svelto.ECS/EntityDescriptor.cs#L2
[2]: ../blob/23580f381d4c3f38416325b889c14862d4b00406/Svelto.ECS/DataStructures/TypeSafeFasterListForECS.cs#L4
[3]: ../blob/23580f381d4c3f38416325b889c14862d4b00406/Svelto.ECS/EnginesRootEntities.cs#L3
[old-dbc]: https://github.com/sebas77/Svelto.Common/blob/533a86b6a8869fd0ef83dc2a7da557b745fd7290/Utilities/DesignByContract.cs#L10

**Comment by sebas77** [comment]
I'll fix it today thanks for reporting! I am thinking to remove svelto common from ECS and tasks but the I am not sure if people will have a harder time to understand what to do

**Comment by DeoVolenteGames** [comment]
Thanks for that. I was trying to use this ECS in a game jam but it was a bit too hard to learn in such a short time.

I think that removing Svelto.Common should be fine as long as it's clearly documented. Some people would probably miss it, so it would also be great if the ECS threw some sort of descriptive error at compile time if Common was missing. Just something that said "X is missing; have you downloaded the Svelto.Common module? *link to download*". I don't know how easy that is to do though.
