### ISSUE TITLE
Visualization of engines, entities, and components in the Unity inspector

### ISSUE THREAD

**Issue by starikcetin** [sebas77/Svelto.ECS#20]
Are planning on developing something Unity inspector functionality in order to view engines, entities, and components? 

It would be even more useful if we could add/remove and pause/resume them at runtime, too, just like with Entitas.

**Comment by sebas77** [comment]
Hello! thanks for the question . The only visual thing right now is the Profiler, which tells you how long Add and Remove callbacks take. However it's not very useful tbh, as initially I was using to profile the loops as well, but now these profiles are done by svelto.Tasks.

I tend to use the editor as less as possible, but nothing stop you or someone else from creating what you need if you wish, then I will link it from everywhere I write :)

**Comment by starikcetin** [comment]
If you don't mind me asking, how are you inspecting what is going on in your game without using the editor?

**Comment by sebas77** [comment]
The only inspection I do with the editor is profiling and console log.
Usually we don't need anything else, what kind of inspection you use
instead?

**Comment by starikcetin** [comment]
I usually tinker around with the GameObject inspector and script variables, to see the value changes. It is very useful when you enable the debug mode. 

That being said, I haven't used an ECS framework before; so my workflow may not make much sense when applied to the ECS context.

**Comment by sebas77** [comment]
I see. With the implementors you can still do that with a sort of data binding system, but I don't suggest to use implementors as monobehavior just to hold data

**Comment by leopripos** [comment]
Hi, I have a **simple** Inspector for Svelto.ECS. You can take a look here:

[https://github.com/NED-Studio/LGK.Inspector](https://github.com/NED-Studio/LGK.Inspector)

[https://github.com/NED-Studio/LGK.Inspector.Example](https://github.com/NED-Studio/LGK.Inspector.Example)

Current feature:
- Svelto.ECS sytle (without MonoBehaviour)
- Using reflection
- Support field and setter/getter
- Support custom component drawer
- Support custom type drawer
- Not support Collection *need suggestion how to implement this :D
- Can't automatically inspect class or struct, you need to create your own type/component drawer

If you have suggestion, please let me know.
:)

**Comment by sebas77** [comment]
This is very cool thanks!! Let me know if you want me to put in the main read me of Svelto

**Comment by starikcetin** [comment]
@leopripos That is very cool. I will try it as soon as I get the chance. Thanks for sharing!

**Comment by leopripos** [comment]
@sebas77 main readme please, thanks :)

@starikcetin thanks bro. let me know if you have any problem with it.

**Comment by leopripos** [comment]
yeah, I'll continuously improve it.

Now, i'm working on array and list support.
:)
