### ISSUE TITLE
Discord or Slack?

### ISSUE THREAD

**Issue by sebas77** [sebas77/Svelto.ECS#21]
I want to open a channel to discuss features with you, do you prefer Discord or Slack?

**Comment by sebas77** [comment]
or maybe just use the Issue list as forum?

**Comment by sebas77** [comment]
hmmm to be honest I would prefer a separate forum as it could serve as documentation as well, maybe I will try to add something on sebaslab

**Comment by starikcetin** [comment]
Gitter is very popular among GitHub users, you might want to check that out as well.

**Comment by sebas77** [comment]
Room created, let's see how it works out

**Comment by sebas77** [comment]
https://gitter.im/Svelto-ECS/Lobby
