### ISSUE TITLE
How to install the 2.0 beta 2 release?

### ISSUE THREAD

**Issue by starikcetin** [sebas77/Svelto.ECS#25]
The latest release zip (2.0 beta 2) doesn't have a .git folder so git doesn't recognize it as a git repository. Therefore I can't initialize submodules.

**Comment by starikcetin** [comment]
For now, I manually cloned Svelto.Common repo in Svelto.Common folder and it seems to be working, is this how it is intended to be done?

**Comment by sebas77** [comment]
Hey there,

I create a release every time I am going to merge a massive refactoring in mainline, just to be sure that if I put any breaking change, the users won't be affected as they can use the previous version.

So if you want to learn, it's always better to use the repository version.

All that said, what a release does is just labeling current files, however Svelto.Common is a submodule so you will need to know which changelist of that Svelto.Common repository the release is pointing to.

The best thing honestly is NOT downloading the zip file, but instead to check the labeled repository. On the left there is a tag:  Rel2b2. If you click on it, you will see the repository labeled at that point. 

You may be able to clone a repository using that label, I never tried. Anyway if you click on it, you will see that Svelto.Commons points at the changelist Svelto.Common @ 460c008

If you click on it (Svelto.Common @ 460c008) that's the Svelto.Common version you need to download if you want to use the zip files.

**Comment by starikcetin** [comment]
Good to know, thank you.
