### ISSUE TITLE
Mega refactoring incoming

### ISSUE THREAD

**Issue by sebas77** [sebas77/Svelto.ECS#29]
among the other things, I am simplifying the code even more, removing the concept of global entities pool (I need to explain this in depth), introducing EntityViewStructs (They are like the entity view, so they will still need the implementors, but with zero allocation cost). 

There are still some pieces that must click in place, but I am getting there.

**Comment by sebas77** [comment]
The functionality will not change (it would break all our current
products), but it won't be possible to retrieve the global list of entity
views regardless the group, a group will be need to be specified always.

**Comment by sebas77** [comment]
if you want to try an early preview of the new Svelto ECS try the Survival example entityviewasstruct branch I am moving toward allocation 0 code, all the entitiviews are now struct of course the implementors are still objects, but I will explain in future when to use EntityViewStructs, EntityStructs and the soon obsolete EntityViews

**Comment by sebas77** [comment]
Boost is the only thing that can make really a difference in my case, but since it still not supported by the standalone client, I haven't tested it yet. It's more related to the jobs system than the ECS, but it can be used outside it too, so I can take advantage of it in Svelto as well.
There are a few other things I want to have a look, but I think I can integrate all of them in Svelto.

**Comment by sebas77** [comment]
haha also it's called burst, not boost, my bad :)

**Comment by SugoiDev** [comment]
We both did it, haha!

**Comment by sebas77** [comment]
Closing this, the refactoring is already available and the article will be published soon.
