### ISSUE TITLE
Unity 5.5.0 breaks Svelto

### ISSUE THREAD

**Issue by Darelbi** [sebas77/Svelto.ECS#3]
Profiling has moved to `UnityEngine.Profiling` namespace, as result

GameObjectFactory.cs, Line 51

do not compile because it can't find the "Profiler" name.

**Comment by sebas77** [comment]
*soon * I'll update it with new features...knowing my soon it will take some weeks :(

**Comment by Darelbi** [comment]
Ahaha don't warry I'm not in hurry
Will Svelto add the chance to add nodes to existing entities? (so that an entity is no longer immutable). :)

**Comment by sebas77** [comment]
It does not make sense to change the nodes of an Entity in real-time, but I want to understand more of your use case.

**Comment by Darelbi** [comment]
I started looking at the code.

For my use case: Entities have a logical part (position / AI/ path-wandering) that is updated regardless of the fact the Entity is visible or not. **But when player is near enough the Entity should add the "Visible" part** (loading the missing graphics eventually). How should one model that in Svelto-ECS? Add a VisibleEntity that follows the "LogicalEntity" only when it is near enough to player camera? 

In a regular ECS one should just add the "visible" component to the entity when it is near enough, here I have to create a Whole new entity "just" for that. I know it does not make sense making things so "dynamic", especially because it could be abused, but maybe I overlooked and there is a simpler/better way to achieve the following that I actually missed in SveltoECS:

- Keep the "Visible" part of an Enemy loaded only when it is near enough to the player

**Comment by sebas77** [comment]
I am not sure what you mean with logical part, but if I understand correctly, what you should do is add the data always, regardless, and manage it through the engines. For example, let the engines now about your mesh renderer since the start, but the engine will enable it only when the entity is close. With Svelto.ECS is not a matter of add or remove, is always a matter of enable or disable.

**Comment by Darelbi** [comment]
Thank you. Yes it makes sense that way. Your approach is atypical but I'm starting to like it. I hope I had more free time to make better use of it.
