### ISSUE TITLE
New article is up

### ISSUE THREAD

**Issue by sebas77** [sebas77/Svelto.ECS#33]
http://www.sebaslab.com/svelto-ecs-2-5-and-allocation-0-code/

it comes together with Svelto 2.5 :)

It will take time to clean it up and test everything properly, but I am ready for feedback!

**Comment by Blucky87** [comment]
Very cool. I briefly skimmed your article and am very glad you decided to keep this project going even with Unity's ECS being developed. I very much like the svelto.ecs approach over the other c# alternatives for monogame.    
I saw that you mentioned not being fully knowledgeable on Unity's ECS. i have watched many of Unity's videos and [this one from Mike Acton](https://www.youtube.com/watch?v=p65Yt20pw0g) walks through it and he is the lead on the project i believe.   
Keep up the good work! I plan on checking out and converting some of my stuff to the 2.5 version.
