### ISSUE TITLE
Recreate entity with same id

### ISSUE THREAD

**Issue by TestLazeR** [sebas77/Svelto.ECS#34]
```
           _entityFactory.BuildEntity<HouseBuildingEntityDescriptor>(101, null);
            yield return new WaitForSecondsEnumerator(2);
            _entityFunctions.RemoveEntity(101);
            yield return new WaitForSecondsEnumerator(2);
            _entityFactory.BuildEntity<HouseBuildingEntityDescriptor>(101, null);
```

i have error, FasterDictionaryException: Key already present.

Why i can't recreate entity with same id?

**Comment by sebas77** [comment]
thanks I didn't notice you added an issue here too. That's what I needed not the github project :P.  I will be back to you asap!

**Comment by TestLazeR** [comment]
Sry)

ср, 4 июл. 2018 г., 16:34 Sebastiano Mandalà <notifications@github.com>:

**Comment by sebas77** [comment]
ok this is now fixed ;)
