### ISSUE TITLE
Cannot restart an IEnumerator without a valid Reset function

### ISSUE THREAD

**Issue by Chaleeshadow** [sebas77/Svelto.ECS#35]
Hello Thank for Svelto.ECS i am a newbie.
I tried to with Photon,Yeah it so excellent but I don't know solve problem  "Cannot restart an IEnumerator without a valid Reset function, use SetEnumeratorProvider instead" Occurs when player host room disconnected already other players will get this error

![w](https://user-images.githubusercontent.com/40860287/42339135-489b9740-80b6-11e8-85e7-b93bab5d89f9.jpg)

my code adapt from Svelto.ECS.Examples.Survival What should i do to solve this problem？
Thanks

**Comment by sebas77** [comment]
there are several ways to solve the problem, but I need to see the code to be sure. If you are using a task routine, don't use a SetEnumerator, but use a SetEnumeratorProvider with a function that returns the enumerator and not the enumerator itself. This is the simples way to do it, although it would allocate a new enumerator every time the task is restarted.

**Comment by Chaleeshadow** [comment]
Thanks. I get it change to SetEnumeratorProvider!!
