### ISSUE TITLE
Incorrect error description thrown

### ISSUE THREAD

**Issue by DanielHazlewood** [sebas77/Svelto.ECS#40]
[Class(EntityBuilder.CheckFields.cs)](https://github.com/sebas77/Svelto.ECS/blob/master/Svelto.ECS/EntityBuilder.CheckFields.cs)
EntityBuilder.CheckFields.Cs on Line 72 describes the error as:
`ProcessError("Entity View Structs must hold entity components interfaces", type);
`
This is incorrect, as the error is thrown when a non-interface is found as a field. This can be confusing, as that's not what the error is checking for.  As it was in my case.

I suggest the change to:
`ProcessError("Entity View Structs must hold only entity components interfaces", type);`

**Comment by sebas77** [comment]
fixed
