### ISSUE TITLE
does it compatible with unity3d?

### ISSUE THREAD

**Issue by moto2002** [sebas77/Svelto.ECS#5]
Hi,does it compatible with unity3d please?

**Comment by Darelbi** [comment]
It works in Unity. It is made for unity. Maybe on older versions There are
few lines of code to be changed since Unity from time to time break stuff
or reorganize namespaces. Try to download and run svelto ecs example

Il 17 mar 2017 11:56, "Jack" <notifications@github.com> ha scritto:
