### ISSUE TITLE
Any chance something like this might work with UnrealCLR?

### ISSUE THREAD

**Issue by MostHated** [sebas77/Svelto.ECS#53]
Hey there,
    I am not sure if you are familiar with [UnrealCLR](https://github.com/nxrighthere/UnrealCLR) but I was playing around with it today and was quite impressed. Being a big fan of Unitys new DOTS implementations, it made me wonder if an ECS platform that is engine agnostic might be able to be used with UnrealCLR? While it might be a bit unfortunate to not have the ease of use that the Job system can provide, having a well established ECS framework in Unreal using C# sounds pretty exciting to me!

Thanks,
-MH

**Comment by sebas77** [comment]
Hi,

I don't see any reason why Svelto.ECS shouldn't work with UnrealCLR. If you want to try, check the mini examples repository, they have all been updated to Svelto.ECS 3.0 that, while not officially announced yet, is what you should do. The vanilla repository is not an Unity project.

Svelto.Tasks 2.0 could be substitute Jobs, but unluckily I have never finished it. It's something I will do once I will be completely happy with Svelto.ECS .
