### ISSUE TITLE
Does Svelto work without Unity? Any gotchas to keep in mind?

### ISSUE THREAD

**Issue by Racso** [sebas77/Svelto.ECS#56]
Hi!

We're currently working on a pure C# Authoritative Server for a mobile game, and we're considering the possibility of switching to an ECS architecture. In short: the server is in charge of simulating the game rules. It does that in discrete ticks, which we run via a single entry point function (i.e. an "Update" function that the server infrastructure calls every X milliseconds). The match status is sent over the network with a certain frequency, and it's used by the clients to display the status.

"Pure C#" means that there's no Unity code whatsoever in the server. We do use third-party libraries (the lighter they are in CPU and memory load, the better).

Do you think Svelto would work for us? If I understand correctly, it can be used without Unity. Is that correct? Would we need to do something "special" or to use any workaround for it to work?

Thanks!

**Comment by Racso** [comment]
After digging a bit more in your articles and documentation, I see that Svelto certainly should work without Unity.

I'll leave this issue opened for a bit more in case you have any comment you'd like to add; feel free to close it if not. Thanks!

**Comment by sebas77** [comment]
@Racso sorry, I was unplugged for one week. Please join our discord server is the best way to stay in touch with me and a lot of other people: https://discord.gg/3qAdjDb

yes Svelto.ECS works without unity and I am actually now working on a new mini example that just uses SDL.
