### ISSUE TITLE
DesignByContract class' methods are not compiled

### ISSUE THREAD

**Issue by slvr-aim** [sebas77/Svelto.ECS#6]
See https://issuetracker.unity3d.com/issues/methods-with-conditional-attributes-arent-fired-if-preprocessor-identifier-isnt-defined-in-the-class-that-calls-that-method

This happens on Unity 2017.1p1

**Comment by sebas77** [comment]
I am updating Svelto.ECS today to the newest version. There could be destructive changes, but the example will compile out of the box
