### ISSUE TITLE
Question about why Svelto's log is default StackTraceLogType.None

### ISSUE THREAD

**Issue by kenshin12269** [sebas77/Svelto.ECS#66]
I found out that when I use Svelto, Debug.Log doesnt show any StackTrace log. Turns out in SlowLoggerUnity class, stacktraceLog is turn off.

It seems there is no way I could override this feature outside of svelto library.

is there a way I could show StackTrace without editting svelto code?

**Comment by sebas77** [comment]
I have fixed it in the new svelto which I don't have an ETA for the release yet, I suggest you to change the code yourself for the moment.

**Comment by kenshin12269** [comment]
> I have fixed it in the new svelto which I don't have an ETA for the release yet, I suggest you to change the code yourself for the moment.

Thanks!
