### ISSUE TITLE
Use `Enum.GetNames` to replace the need of a struct for `ISequenceOrder`

### ISSUE THREAD

**Issue by Deuchier** [sebas77/Svelto.ECS#67]
C# has a static method: `Enum.GetNames` which returns an array of entries in the enum. We can use that to reduce boilerplate
for sequential engine groups.

**Comment by sebas77** [comment]
Hi, thanks for the suggestion, however the current enum design to define sequential engines is not casual, it has a specific reason to exist.

It shows the reason once you start to work with different assemblies and asmdefs, its meaning is to not create dependencies between assemblies, using types directly (enums), when this is not necessary.

I know it looks a bit cumbersome, but it pays off once you start to work with more complex projects.

**Comment by Deuchier** [comment]
> 
> 
> Hi, thanks for the suggestion, however the current enum design to define sequential engines is not casual, it has a specific reason to exist.
> 
> It shows the reason once you start to work with different assemblies and asmdefs, its meaning is to not create dependencies between assemblies, using types directly (enums), when this is not necessary.
> 
> I know it looks a bit cumbersome, but it pays off once you start to work with more complex projects.

Thanks for your reply. I will keep that in mind when I see bigger projects in the future.
