### ISSUE TITLE
`SortedJobifiedEnginesGroup` does not implement `IJobifiedEngine`

### ISSUE THREAD

**Issue by Deuchier** [sebas77/Svelto.ECS#69]
`SortedJobifiedEnginesGroup` should be able to be used as an `IJobifiedEngine`, but it does not implement `IJobifiedEngine`.
![image](https://user-images.githubusercontent.com/41805900/123506954-7d921c80-d699-11eb-847b-aed5bf6badde.png)

**Comment by sebas77** [comment]
ok I fixed this in my local stream, but you can just add the interface and it will work.
