### ISSUE TITLE
GroupHashMap throws exception when serializing entity in group using bytemask

### ISSUE THREAD

**Issue by Grigler** [sebas77/Svelto.ECS#74]
GroupHashMap doesn't make use of bytemask in groups when initializing its dictionary, however the Equals function for ExclusiveGroupStruct throws an exception if the bytemask doesn't match. Easiest repo for this is to serialize an entity in a disabled group

**Comment by sebas77** [comment]
hmm @Grigler it's probably best to have a unit test for this too, can you add one if it makes sense?

**Comment by sebas77** [comment]
moved to svelto.ecs.tests
