### ISSUE TITLE
[Ask] Why using C# Reflection?

### ISSUE THREAD

**Issue by leopripos** [sebas77/Svelto.ECS#8]
Hello @sebas77,

I just get started using your framework. I like it.

I have question in my mind why are you using C# Reflection?
As we know, reflection is slow.

**Comment by sebas77** [comment]
C# is built with reflection in mind, so not all the reflection operation are slow, for example is and as are not that slow. However functions to find members on a class are slower. In Svelto reflection is used only during the building of entities. Building of entities should happen rarely or just during the initialization time. If it happens rarely it won't impact your frame rate. If you have to allocate hundreds of entities in run time, then there is something wrong to start with. You have two options at that point, you can enable/disable the entities or pool them. Disable and enable nodes is an option built-in in the framework while pooling is something I will add in future. I will try to explain this better with my next article.

**Comment by leopripos** [comment]
I think it is clear enough
I am waiting for your next article 
:)

Thanks
