### ISSUE TITLE
Missing `UnityEngine' using directive

### ISSUE THREAD

**Issue by leopripos** [sebas77/Svelto.ECS#9]
https://github.com/sebas77/Svelto.ECS/blob/ed9e073ff17c98f44be43e3f741215daea30e2b0/ECS/EnginesRoot.cs#L52

When enable engine profiler, it show error

> Svelto-ECS/ECS/EnginesRoot.cs(52,4): error CS0246: The type or namespace name `GameObject' could not be found. Are you missing `UnityEngine' using directive?

It should changed to this

> UnityEngine.GameObject debugEngineObject = new UnityEngine.GameObject ("Engine Debugger");

**Comment by sebas77** [comment]
Thanks, is a while I don't enable the profiler so it very well be. I'll fix it with the next update (some interesting changes are coming)

**Comment by leopripos** [comment]
You make me curious by "interesting changes are coming"
I hope it's article also coming
:)

**Comment by sebas77** [comment]
This is now fixed, later I will fix the other issue and create a release.
